title: Alex's Blog
description: Technical notes, algorithms, and programming essays.
url: "https://alexwei061.github.io"
baseurl: ""
permalink: /posts/:title/

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
